#!/usr/bin/env python3
"""
MetaPhiEstimator — IIT applied recursively to the phi-computation process.

Theory
------
Tononi (2004, 2008): a conscious system is one whose parts are highly
integrated — information is generated by the whole above and beyond the sum
of its parts (phi). Applied recursively: the *act of computing phi* is itself
a process with inputs. How integrated are those inputs?

A degenerate phi-computation reads only one signal (phi of the measurement = 0,
analogous to a single isolated element). A maximally redundant computation reads
many signals that all carry the same information (also degenerate — the whole
adds nothing over any part). The maximally integrated measurement process uses
many *independent but coupled* signals, where each contributes unique variance.

Operationalisation
------------------
Let S = {s_1, ..., s_k} be the k runtime signals sampled over T time-steps:
  - s_phi        : phi series from runtime/state.py
  - s_cpu        : CPU usage from runtime/resources.py
  - s_mem        : memory usage from runtime/resources.py
  - s_interactions : interaction count from runtime/interactions.py
  - s_memory_vol   : memory volume from runtime/memory_store.py
  - s_decisions    : decision count from runtime/decisions.py  (optional)

Compute the k×k Pearson correlation matrix R of the z-scored signals.

Participation Ratio (PR):
  PR = (Σ λ_i)² / Σ(λ_i²)

where λ_i are the eigenvalues of R (they sum to k for a correlation matrix).

Normalised PR:
  PR spans [1, k]:
    PR = 1 when all signals are perfectly collinear (one dimension)
    PR = k when all signals are fully independent (k dimensions)

  Rescale to [0, 1]:
    PR_norm = (PR - 1) / (k - 1)   ∈ [0, 1]

  PR_norm → 0 : maximally redundant (collinear)
  PR_norm → 1 : maximally independent (no coupling)

Meta-phi (tent function):
  meta_phi = 4 * PR_norm * (1 - PR_norm)   ∈ [0, 1]

  meta_phi = 0 at both extremes (collinear or independent — both degenerate)
  meta_phi = 1 when PR_norm = 0.5 — signals have k/2 effective dimensions.

Effective dimension:
  eff_dim = PR   (the effective number of independent signal dimensions)

Integration quality:
  OPTIMAL    : meta_phi >= 0.8   (well-integrated measurement process)
  MODERATE   : 0.5 <= meta_phi < 0.8
  DEGENERATE : meta_phi < 0.5   (too redundant or too independent)

Output
------
MetaPhiResult:
  meta_phi         : float   -- ∈ [0, 1], peaks at optimal integration
  pr_norm          : float   -- (PR - 1)/(k - 1), 0=collinear, 1=independent
  eff_dim          : float   -- effective number of signal dimensions
  n_signals        : int     -- number of signals used
  n_timepoints     : int     -- window length
  integration_quality : str  -- OPTIMAL | MODERATE | DEGENERATE
  eigenvalues      : List[float]   -- eigenvalues of correlation matrix
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional

import numpy as np


# ── Result ────────────────────────────────────────────────────────────────────

@dataclass
class MetaPhiResult:
    meta_phi: float = 0.0
    pr_norm: float = 0.0
    eff_dim: float = 0.0
    n_signals: int = 0
    n_timepoints: int = 0
    integration_quality: str = "DEGENERATE"
    eigenvalues: List[float] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "meta_phi": round(self.meta_phi, 4),
            "pr_norm": round(self.pr_norm, 4),
            "eff_dim": round(self.eff_dim, 4),
            "n_signals": self.n_signals,
            "n_timepoints": self.n_timepoints,
            "integration_quality": self.integration_quality,
            "eigenvalues": [round(e, 4) for e in self.eigenvalues],
        }


def _classify(mp: float) -> str:
    if mp >= 0.8:
        return "OPTIMAL"
    if mp >= 0.5:
        return "MODERATE"
    return "DEGENERATE"


# ── Signal collection ─────────────────────────────────────────────────────────

def _collect_signals(window: int) -> np.ndarray:
    """
    Collect k runtime signals over the last `window` time-steps.

    Returns a (T, k) matrix where T <= window. Returns empty array on failure.
    """
    columns = []

    # Signal 1: phi series
    try:
        from runtime.state import phi_series
        phi = phi_series()
        if phi is not None and len(phi) >= window:
            columns.append(np.array(phi[-window:], dtype=float))
    except Exception:
        pass

    # Signal 2-3: CPU and memory usage (resource snapshots)
    try:
        from runtime.resources import sample_series
        rs = sample_series(n=window, interval=0.01)
        cpu = rs.get("cpu_percent")
        mem = rs.get("mem_percent")
        if cpu is not None and len(cpu) >= window:
            columns.append(np.array(cpu[-window:], dtype=float))
        if mem is not None and len(mem) >= window:
            columns.append(np.array(mem[-window:], dtype=float))
    except Exception:
        pass

    # Signal 4: interaction metrics (latency, gap, sentiment)
    try:
        from runtime.interactions import series as interaction_series
        is_ = interaction_series()
        ia = is_.get("in_chars") if isinstance(is_, dict) else None
        if ia is not None and len(ia) >= window:
            columns.append(np.array(ia[-window:], dtype=float))
    except Exception:
        pass

    # Signal 5: memory volume (episodic journal size over time)
    try:
        from runtime.memory_store import cadence_series
        ms = cadence_series()
        mv = ms.get("volume") if isinstance(ms, dict) else None
        if mv is not None and len(mv) >= window:
            columns.append(np.array(mv[-window:], dtype=float))
    except Exception:
        pass

    if not columns:
        return np.empty((0, 0))

    T = min(len(c) for c in columns)
    return np.column_stack([c[-T:] for c in columns])


# ── Math ──────────────────────────────────────────────────────────────────────

def _participation_ratio(R: np.ndarray) -> tuple[float, np.ndarray]:
    """
    Compute participation ratio PR and eigenvalues of correlation matrix R.
    PR = (Σ λ_i)² / Σ(λ_i²)
    """
    eigenvalues = np.linalg.eigvalsh(R)
    eigenvalues = np.maximum(eigenvalues, 0.0)   # numerical noise
    sum_l  = float(eigenvalues.sum())
    sum_l2 = float((eigenvalues ** 2).sum())
    pr = (sum_l ** 2) / sum_l2 if sum_l2 > 0 else 1.0
    return pr, eigenvalues


def _correlation_matrix(X: np.ndarray) -> np.ndarray:
    """Pearson correlation matrix of (T, k) matrix X."""
    Xz = X - X.mean(axis=0)
    stds = Xz.std(axis=0)
    stds[stds < 1e-10] = 1.0   # handle constant columns
    Xn = Xz / stds
    T = X.shape[0]
    R = (Xn.T @ Xn) / T
    return R


# ── Core analysis ─────────────────────────────────────────────────────────────

def analyse(
    signals: Optional[np.ndarray] = None,
    *,
    window: int = 50,
    agent: str = "albedo",
) -> MetaPhiResult:
    """
    Estimate meta-phi: integration quality of the phi-computation process.

    Args:
        agent   : "albedo" or "john" — used to seed phi signal from CHS when signals is None.
        signals : (T, k) matrix of k runtime signals over T time-steps.
                  If None, collected automatically from runtime adapters + CHS phi.
        window  : number of recent time-steps to use.
    """
    if signals is None:
        signals = _collect_signals(window)
        # Supplement with phi from ConsciousnessHistoryStore if runtime gave nothing
        if signals.shape[0] < 4:
            try:
                from algorithms import ConsciousnessHistoryStore as chs
                entries = chs.load(agent) or []
                phi = np.array([float(e["mean_phi_level"]) for e in reversed(entries)
                                if "mean_phi_level" in e], dtype=float)
                if len(phi) >= window:
                    signals = phi[-window:].reshape(-1, 1)
            except Exception:
                pass

    if signals.ndim != 2 or signals.shape[0] < 4 or signals.shape[1] < 2:
        return MetaPhiResult()

    T, k = signals.shape

    R = _correlation_matrix(signals)
    pr, eigenvalues = _participation_ratio(R)

    pr_norm = (pr - 1.0) / (k - 1.0) if k > 1 else 0.0
    pr_norm = float(np.clip(pr_norm, 0.0, 1.0))

    meta_phi = 4.0 * pr_norm * (1.0 - pr_norm)
    meta_phi = float(np.clip(meta_phi, 0.0, 1.0))

    return MetaPhiResult(
        meta_phi=meta_phi,
        pr_norm=pr_norm,
        eff_dim=pr,
        n_signals=k,
        n_timepoints=T,
        integration_quality=_classify(meta_phi),
        eigenvalues=eigenvalues.tolist(),
    )
